name: Action PR opened
on:
  pull_request:
    branches:  
      - feature/github-actions
    types:
      - opened
      - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GITHUB_ACCESS_TOKEN = ${{ github.token }}"
      - run: echo "MOODLE_ACCESS_TOKEN = 'from file'"
      - run: echo "GITHUB_REPO = ${{ github.repository }}"
      - run: echo "GITHUB_PR_ID = ${{github.event.number}}"
      # 
      - run: echo "pr title - ${{ github.event.pull_request.title }}"
      - run: echo "github - ${{ toJSON(github) }}"
      # 

      steps:
      - name: Build docker images
        run: docker build -t scripts .
      - name: Run tests
        run: docker run scripts --rm scripts python main.py script1 mock 3
      # - run: docker run \
      #         -e GITHUB_ACCESS_TOKEN="${{ github.token }}" \
      #         -e MOODLE_ACCESS_TOKEN=${{ secrets.MOODLE_ACCESS_TOKEN }} \
      #         -e GITHUB_REPO="${{ github.repository }}" \
      #         -e GITHUB_PR_ID="${{github.event.number}}" \
      #         --rm \
      #         scripts\
      #         python main.py\
      #         script1 mock 3

      - run: echo "🍏 This job's status is ${{ job.status }}."