name: scr 2 
on:
  schedule:
    - cron: '*/2 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: cron 1
        if: github.event.schedule == '*/2 * * * *'
        run: echo "params for current time 1"
      - name: cron 2
        if: github.event.schedule != '*/2 * * * *'
        run: echo "params for current time 2"
      - 
        name: Check out code
        uses: actions/checkout@v2
      - 
        name: Build docker images
        run: docker build -t scripts .
      - 
        name: Run script
        run: docker run -e COURSE_ID=47 -e CM_ID=1553 -e GITHUB_REPO="${{ github.repository }}" -e GITHUB_PR_REGEX="^(\\w*)_(lr1)$" -e GITHUB_ACCESS_TOKEN="${{ github.token }}" -e MOODLE_ACCESS_TOKEN="${{ secrets.MOODLE_ACCESS_TOKEN }}" scripts python main.py script2 mock 1

      - run: echo "🍏 This job's status is ${{ job.status }}."