name: scr 2 
on:
  schedule:
    - cron: '*/1 * * * *'
    - cron: '*/2 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GITHUB_ACCESS_TOKEN = ${{ github.token }}"
      - run: echo "MOODLE_ACCESS_TOKEN = ${{ secrets.MOODLE_ACCESS_TOKEN }}"
      - run: echo "GITHUB_REPO = ${{ github.repository }}"
      - run: echo "GITHUB_PR_REGEX = ^(\\w*)_(lr1)$"
      - run: echo "pr title - ${{ github.event.pull_request.title }}"
      - 
        name: Check out code
        uses: actions/checkout@v2
      - 
        name: Build docker images
        run: docker build -t scripts .
      - 
        name: Run script
        run: docker run -e COURSE_ID=47 -e CM_ID=1553 -e GITHUB_REPO="${{ github.repository }}" -e GITHUB_PR_REGEX="^(\\w*)_(lr1)$" -e GITHUB_ACCESS_TOKEN="${{ github.token }}" -e MOODLE_ACCESS_TOKEN="${{ secrets.MOODLE_ACCESS_TOKEN }}" scripts python main.py script2 mock 1

      - run: echo "🍏 This job's status is ${{ job.status }}."